create table
  public.samples_info (
    id bigint not null,
    FD sample ID text null,
    FD Run ID text null,
    Strain text null,
    EFT date date null,
    Broth ID text null,
    Fermentation scale text null,
    Ferm condition text null,
    EFT (hr) bigint null,
    Broth titer (CFU / mL) bigint null,
    Broth age (day) bigint null,
    Pelletization date date null,
    Cryo mix text null,
    Ingredient 1 text null,
    Ingredient 2 text null,
    Ingredient 3 text null,
    Cryo mix addition rate double precision null,
    FD start date date null,
    FD recipe text null,
    FD pressure (mTorr) text null,
    FD run time(hr) double precision null,
    primary ramp rate (C / min) text null,
    PA receive date date null,
    Dried appearance text null,
    Container text null,
    Water activity double precision null,
    Viability (CFU / g) bigint null,
    Cryo mix Coef double precision null,
    constraint samples_info_pkey primary key (id)
  ) tablespace pg_default;
